export const FIELDS_DATA = [
  {"id":1,"block":"Johnston Block 1","ranch":"Johnston","variety":"Kaweah","crop":"Freestone Peach","acres":33},
  {"id":2,"block":"Johnston Block 2","ranch":"Johnston","variety":"Zee Lady","crop":"Freestone Peach","acres":18.5},
  {"id":3,"block":"Johnston Block 3A","ranch":"Johnston","variety":"Zee Lady","crop":"Freestone Peach","acres":18.5},
  {"id":4,"block":"Johnston Block 3B","ranch":"Johnston","variety":"Angelus","crop":"Freestone Peach","acres":18.5},
  {"id":5,"block":"Johnston Block 4","ranch":"Johnston","variety":"Parade","crop":"Freestone Peach","acres":13},
  {"id":6,"block":"Johnston Block 5A","ranch":"Johnston","variety":"Tra Zee","crop":"Freestone Peach","acres":15},
  {"id":7,"block":"Johnston block 5B","ranch":"Johnston","variety":"Angelus","crop":"Freestone Peach","acres":15},
  {"id":8,"block":"Johnston Block 56/58","ranch":"Johnston","variety":"Autumn Flame","crop":"Freestone Peach","acres":30},
  {"id":9,"block":"Johnston Block 36A","ranch":"Johnston","variety":"Carnival","crop":"Freestone Peach","acres":18.5},
  {"id":10,"block":"Johnston Block 36B","ranch":"Johnston","variety":"Kaweah","crop":"Freestone Peach","acres":18.5},
  {"id":11,"block":"Johnston Block 39","ranch":"Johnston","variety":"Carnival","crop":"Freestone Peach","acres":17},
  {"id":12,"block":"Johnston Block 40","ranch":"Johnston","variety":"Fairtime","crop":"Freestone Peach","acres":21},
  {"id":13,"block":"Johnston Block 35","ranch":"Johnston","variety":"Butte/Padre","crop":"Almond","acres":17},
  {"id":14,"block":"Blue Lupin Block 17","ranch":"Blue Lupin","variety":"Nonpareil","crop":"Almond","acres":21},
  {"id":15,"block":"Blue Lupin Block 18","ranch":"Blue Lupin","variety":"Zee Lady","crop":"Freestone Peach","acres":19},
  {"id":16,"block":"Blue Lupin Block 19","ranch":"Blue Lupin","variety":"Butte/Padre","crop":"Almond","acres":35},
  {"id":17,"block":"Blue Lupin Block 21","ranch":"Blue Lupin","variety":"Nonpareil/Monterey","crop":"Almond","acres":23.5},
  {"id":18,"block":"Blue Lupin Block 10","ranch":"Blue Lupin","variety":"Fairtime","crop":"Freestone Peach","acres":30},
  {"id":19,"block":"Blue Lupin Block 8/9","ranch":"Blue Lupin","variety":"Butte/Padre","crop":"Almond","acres":38.5},
  {"id":20,"block":"Fagundes Block 64A","ranch":"Fagundes","variety":"Independence","crop":"Almond","acres":20},
  {"id":21,"block":"Fagundes Block 64B","ranch":"Fagundes","variety":"Late Ross","crop":"Cling Peach","acres":20},
  {"id":22,"block":"Fagundes Block 65B","ranch":"Fagundes","variety":"Klamath","crop":"Cling Peach","acres":14},
  {"id":23,"block":"Fagundes Block 65A","ranch":"Fagundes","variety":"Late Ross","crop":"Cling Peach","acres":13},
  {"id":24,"block":"Fagundes Block 67A","ranch":"Fagundes","variety":"Autumn Flame","crop":"Freestone Peach","acres":18},
  {"id":25,"block":"Fagundes Block 67B","ranch":"Fagundes","variety":"Kaweah","crop":"Freestone Peach","acres":15},
  {"id":26,"block":"Fagundes Block 70A","ranch":"Fagundes","variety":"Carnival","crop":"Freestone Peach","acres":20},
  {"id":27,"block":"Fagundes Block 70B","ranch":"Fagundes","variety":"Fairtime","crop":"Freestone Peach","acres":19},
  {"id":28,"block":"Fagundes Block 71","ranch":"Fagundes","variety":"Angelus","crop":"Freestone Peach","acres":9},
  {"id":29,"block":"Fagundes Block 72A","ranch":"Fagundes","variety":"Parade","crop":"Freestone Peach","acres":16},
  {"id":30,"block":"Fagundes Block 72B","ranch":"Fagundes","variety":"July Flame","crop":"Freestone Peach","acres":11},
  {"id":31,"block":"Fagundes Block 73","ranch":"Fagundes","variety":"Angelus","crop":"Freestone Peach","acres":19},
  {"id":32,"block":"Fagundes Block 74A","ranch":"Fagundes","variety":"Kaweah","crop":"Freestone Peach","acres":20},
  {"id":33,"block":"Fagundes Block 74B","ranch":"Fagundes","variety":"Zee Lady","crop":"Freestone Peach","acres":22},
  {"id":34,"block":"Fagundes Block 76A","ranch":"Fagundes","variety":"Fay Elberta","crop":"Freestone Peach","acres":10},
  {"id":35,"block":"Fagundes Block 76B","ranch":"Fagundes","variety":"Elegant Lady","crop":"Freestone Peach","acres":20},
  {"id":36,"block":"Fagundes Block 66","ranch":"Fagundes","variety":"Independence","crop":"Almond","acres":27},
  {"id":37,"block":"Fagundes Block 68","ranch":"Fagundes","variety":"Independence","crop":"Almond","acres":35},
  {"id":38,"block":"Fagundes Block 75","ranch":"Fagundes","variety":"Independence","crop":"Almond","acres":26},
  {"id":39,"block":"Fagundes Block 77","ranch":"Fagundes","variety":"Independence","crop":"Almond","acres":26},
  {"id":40,"block":"Fagundes Block 61","ranch":"Fagundes","variety":"Independence","crop":"Almond","acres":17},
  {"id":41,"block":"Fagundes Block 62","ranch":"Fagundes","variety":"Independence","crop":"Almond","acres":27},
  {"id":42,"block":"Fagundes Block 63","ranch":"Fagundes","variety":"Independence","crop":"Almond","acres":32},
  {"id":43,"block":"Fagundes Block 60","ranch":"Fagundes","variety":"Independence","crop":"Almond","acres":28},
  {"id":44,"block":"Fagundes Mello","ranch":"Mello","variety":"Independence","crop":"Almond","acres":35},
  {"id":45,"block":"Fagundes Angel Ranch","ranch":"Angel Ranch","variety":"Nonpareil/Monterey/Carmel","crop":"Almond","acres":17}
];

export default FIELDS_DATA;
