'use client';

import { useEffect, useMemo, useState } from "react";

// Shape of /harvest.json, generated by the Farm-manager-bot. See
// harvest_export.py:build_snapshot for the source of truth.
type Entry = {
  date: string;        // YYYY-MM-DD (bot/local time)
  field_id: string;
  block: string;
  variety: string;
  acres: number | null;
  bins: number;
};

type DayRow = { date: string; bins: number };

type BlockRow = {
  field_id: string;
  block: string;
  variety: string;
  acres: number | null;
  bins: number;
  bins_per_acre: number | null;
};

type Snapshot = {
  generated_at: string;
  entries: Entry[];
  per_day: DayRow[];
  per_block: BlockRow[];
  totals: {
    bins: number;
    entries: number;
    blocks: number;
    first_date: string | null;
    last_date: string | null;
  };
};

// How many days of bars to show in the trend chart.
const TREND_DAYS = 30;

// Treat the snapshot as "stale" if it's older than this (just for the UX hint).
const STALE_AFTER_MS = 6 * 60 * 60 * 1000; // 6 hours

const card: React.CSSProperties = {
  backgroundColor: 'white',
  borderRadius: '24px',
  padding: '24px',
  boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)',
};

const sectionTitle: React.CSSProperties = {
  fontSize: '22px',
  fontWeight: 600,
  marginBottom: '4px',
};

const subtitle: React.CSSProperties = {
  color: '#666',
  fontSize: '13px',
};

function fmtDate(iso: string): string {
  // Format YYYY-MM-DD as "May 29" — explicit T00:00 so we don't shift TZ.
  const d = new Date(iso + 'T00:00:00');
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
}

function fmtGeneratedAt(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString();
}

function fillMissingDays(rows: DayRow[], n: number): DayRow[] {
  // Build the last n calendar days ending today, filling 0-bin days so the
  // chart bars are evenly spaced and the timeline is honest.
  const out: DayRow[] = [];
  const byDate = new Map(rows.map(r => [r.date, r.bins]));
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  for (let i = n - 1; i >= 0; i--) {
    const d = new Date(today);
    d.setDate(today.getDate() - i);
    const iso = d.toISOString().slice(0, 10);
    out.push({ date: iso, bins: byDate.get(iso) ?? 0 });
  }
  return out;
}

export default function Harvest() {
  const [data, setData] = useState<Snapshot | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      setLoading(true);
      setError(null);
      try {
        // Cache-bust so a fresh deploy always reads the latest snapshot. The
        // file is committed by the bot, so a Vercel rebuild is what makes
        // new data appear; this just defeats any aggressive CDN caching.
        const res = await fetch(`/harvest.json?ts=${Date.now()}`, {
          cache: 'no-store',
        });
        if (res.status === 404) {
          if (!cancelled) {
            setData(null);
            setError('no-snapshot');
          }
          return;
        }
        if (!res.ok) throw new Error(`Harvest snapshot responded ${res.status}`);
        const json = await res.json() as Snapshot;
        if (!cancelled) setData(json);
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : 'Failed to load harvest data');
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    load();
    return () => { cancelled = true; };
  }, []);

  const trend = useMemo(
    () => (data ? fillMissingDays(data.per_day, TREND_DAYS) : []),
    [data],
  );
  const maxBins = useMemo(
    () => trend.reduce((m, r) => Math.max(m, r.bins), 0),
    [trend],
  );
  const stale = useMemo(() => {
    if (!data) return false;
    const t = new Date(data.generated_at).getTime();
    return Number.isFinite(t) && Date.now() - t > STALE_AFTER_MS;
  }, [data]);

  if (loading) {
    return (
      <div style={card} data-testid="harvest-loading">
        <h2 style={sectionTitle}>Harvest</h2>
        <p style={{ color: '#666' }}>Loading harvest snapshot…</p>
      </div>
    );
  }

  if (error === 'no-snapshot') {
    return (
      <div style={card} data-testid="harvest-empty">
        <h2 style={sectionTitle}>Harvest</h2>
        <p style={{ color: '#666', marginBottom: '12px' }}>
          No harvest data yet. As soon as you log entries from the
          Farm-manager-bot (e.g. &ldquo;Block 4 18 bins&rdquo; in Telegram),
          they&rsquo;ll appear here on the next deploy.
        </p>
        <p style={{ fontSize: '13px', color: '#888' }}>
          Setup: the bot needs a GitHub fine-grained PAT with
          Contents:Read+Write on this repo, stored on Render as
          <code style={{ margin: '0 4px' }}>HARVEST_EXPORT_PAT</code>.
          See the bot README for details.
        </p>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div style={card} data-testid="harvest-error">
        <h2 style={sectionTitle}>Harvest unavailable</h2>
        <p style={{ color: '#a33', marginBottom: '8px' }}>{error ?? 'No data'}</p>
        <p style={{ color: '#666', fontSize: '13px' }}>
          The harvest snapshot is served as a static file in
          <code style={{ margin: '0 4px' }}>public/harvest.json</code>. If it
          failed to load, try refreshing or check that the latest deploy
          succeeded.
        </p>
      </div>
    );
  }

  const t = data.totals;
  const today = new Date().toISOString().slice(0, 10);
  const todays = data.entries.filter(e => e.date === today);
  const todaysBins = todays.reduce((s, e) => s + e.bins, 0);

  return (
    <div style={{ display: 'grid', gap: '16px' }} data-testid="harvest-panel">
      {/* Headline KPI strip */}
      <div style={card}>
        <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: '16px', alignItems: 'flex-start' }}>
          <div>
            <h2 style={sectionTitle}>Harvest</h2>
            <p style={subtitle}>
              Last updated {fmtGeneratedAt(data.generated_at)}
              {stale && (
                <span style={{ marginLeft: '8px', color: '#a33' }}>
                  &middot; data may be stale
                </span>
              )}
            </p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <p
              style={{ fontSize: '48px', fontWeight: 700, color: '#C55A2E', lineHeight: 1 }}
              data-testid="harvest-bins-today"
            >
              {todaysBins}
            </p>
            <p style={{ color: '#555' }}>bins today</p>
            <p style={{ fontSize: '12px', color: '#888' }}>{todays.length} entries</p>
          </div>
        </div>
        <div
          style={{
            marginTop: '20px',
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
            gap: '12px',
          }}
        >
          <Stat label="Season Total" value={`${t.bins} bins`} />
          <Stat label="Tons (est.)" value={`${(t.bins / 2).toFixed(1)} t`} />
          <Stat label="Entries Logged" value={`${t.entries}`} />
          <Stat label="Blocks Picked" value={`${t.blocks}`} />
          <Stat
            label="Season Range"
            value={
              t.first_date && t.last_date
                ? `${fmtDate(t.first_date)} – ${fmtDate(t.last_date)}`
                : '—'
            }
          />
        </div>
      </div>

      {/* Daily trend chart */}
      <div style={card}>
        <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '4px' }}>
          Bins per Day &mdash; Last {TREND_DAYS} Days
        </h3>
        <p style={subtitle}>One bar per day. Zero-bin days are shown for context.</p>
        <div
          style={{
            marginTop: '16px',
            display: 'flex',
            alignItems: 'flex-end',
            gap: '4px',
            height: '180px',
            overflowX: 'auto',
            paddingBottom: '6px',
          }}
          data-testid="harvest-trend"
          role="img"
          aria-label={`Bins per day for the last ${TREND_DAYS} days`}
        >
          {trend.map(row => {
            const pct = maxBins > 0 ? (row.bins / maxBins) * 100 : 0;
            // Always reserve at least 2px so empty days are visible as
            // ticks rather than vanishing entirely.
            const heightPct = row.bins > 0 ? Math.max(pct, 4) : 2;
            return (
              <div
                key={row.date}
                title={`${fmtDate(row.date)}: ${row.bins} bins`}
                style={{
                  flex: '1 0 18px',
                  minWidth: '18px',
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  justifyContent: 'flex-end',
                  height: '100%',
                }}
              >
                <div
                  style={{
                    width: '100%',
                    height: `${heightPct}%`,
                    backgroundColor: row.bins > 0 ? '#C55A2E' : '#E5DCC5',
                    borderRadius: '4px 4px 0 0',
                  }}
                />
              </div>
            );
          })}
        </div>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            fontSize: '11px',
            color: '#888',
            marginTop: '6px',
          }}
        >
          <span>{trend.length > 0 ? fmtDate(trend[0].date) : ''}</span>
          <span>peak {maxBins} bins/day</span>
          <span>{trend.length > 0 ? fmtDate(trend[trend.length - 1].date) : ''}</span>
        </div>
      </div>

      {/* Today's log */}
      <div style={card}>
        <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '4px' }}>
          Today&rsquo;s Log
        </h3>
        <p style={subtitle}>
          {todays.length === 0
            ? 'No entries logged today yet. Send a message to the bot like “Block 4 18 bins”.'
            : `${todays.length} ${todays.length === 1 ? 'entry' : 'entries'} so far — ${todaysBins} bins total.`}
        </p>
        {todays.length > 0 && (
          <div style={{ overflowX: 'auto', marginTop: '12px' }}>
            <table
              style={{ width: '100%', borderCollapse: 'collapse', fontSize: '14px' }}
              data-testid="harvest-today-table"
            >
              <thead>
                <tr style={{ textAlign: 'left', color: '#666', borderBottom: '1px solid #E5DCC5' }}>
                  <th style={{ padding: '8px 12px' }}>Block</th>
                  <th style={{ padding: '8px 12px' }}>Variety</th>
                  <th style={{ padding: '8px 12px', textAlign: 'right' }}>Acres</th>
                  <th style={{ padding: '8px 12px', textAlign: 'right' }}>Bins</th>
                </tr>
              </thead>
              <tbody>
                {todays
                  .slice()
                  .reverse() // latest first
                  .map((e, i) => (
                    <tr
                      key={`${e.field_id}-${i}`}
                      style={{ borderBottom: '1px solid #F4EEE0' }}
                    >
                      <td style={{ padding: '8px 12px', fontWeight: 500 }}>
                        {e.block || `Field ${e.field_id}`}
                      </td>
                      <td style={{ padding: '8px 12px', color: '#555' }}>{e.variety}</td>
                      <td style={{ padding: '8px 12px', textAlign: 'right', color: '#555' }}>
                        {e.acres ?? '—'}
                      </td>
                      <td style={{ padding: '8px 12px', textAlign: 'right', fontWeight: 600, color: '#C55A2E' }}>
                        {e.bins}
                      </td>
                    </tr>
                  ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Block leaderboard */}
      <div style={card}>
        <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '4px' }}>
          Block Leaderboard
        </h3>
        <p style={subtitle}>
          Season-to-date bins per block, plus bins/acre productivity.
        </p>
        {data.per_block.length === 0 ? (
          <p style={{ color: '#666', marginTop: '12px' }}>No bins logged yet.</p>
        ) : (
          <div style={{ overflowX: 'auto', marginTop: '12px' }}>
            <table
              style={{ width: '100%', borderCollapse: 'collapse', fontSize: '14px' }}
              data-testid="harvest-leaderboard"
            >
              <thead>
                <tr style={{ textAlign: 'left', color: '#666', borderBottom: '1px solid #E5DCC5' }}>
                  <th style={{ padding: '8px 12px', width: '40px' }}>#</th>
                  <th style={{ padding: '8px 12px' }}>Block</th>
                  <th style={{ padding: '8px 12px' }}>Variety</th>
                  <th style={{ padding: '8px 12px', textAlign: 'right' }}>Acres</th>
                  <th style={{ padding: '8px 12px', textAlign: 'right' }}>Bins</th>
                  <th style={{ padding: '8px 12px', textAlign: 'right' }}>Bins / Acre</th>
                </tr>
              </thead>
              <tbody>
                {data.per_block.map((b, i) => (
                  <tr
                    key={b.field_id}
                    style={{ borderBottom: '1px solid #F4EEE0' }}
                  >
                    <td style={{ padding: '8px 12px', color: '#888' }}>{i + 1}</td>
                    <td style={{ padding: '8px 12px', fontWeight: 500 }}>
                      {b.block || `Field ${b.field_id}`}
                    </td>
                    <td style={{ padding: '8px 12px', color: '#555' }}>{b.variety}</td>
                    <td style={{ padding: '8px 12px', textAlign: 'right', color: '#555' }}>
                      {b.acres ?? '—'}
                    </td>
                    <td style={{ padding: '8px 12px', textAlign: 'right', fontWeight: 600, color: '#C55A2E' }}>
                      {b.bins}
                    </td>
                    <td style={{ padding: '8px 12px', textAlign: 'right', color: '#555' }}>
                      {b.bins_per_acre ?? '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
        <p style={{ fontSize: '11px', color: '#888', marginTop: '14px' }}>
          Data: <code>public/harvest.json</code>, written by the Farm-manager-bot
          after each <em>Block X N bins</em> message in Telegram. 1 bin ≈ 1,000 lbs
          (0.5 ton). Bins/acre is season-to-date and does not account for partial
          picks.
        </p>
      </div>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ backgroundColor: '#F4EEE0', borderRadius: '14px', padding: '14px', textAlign: 'center' }}>
      <p style={{ fontSize: '11px', textTransform: 'uppercase', color: '#888', letterSpacing: '0.04em' }}>{label}</p>
      <p style={{ fontSize: '18px', fontWeight: 600, color: '#333' }}>{value}</p>
    </div>
  );
}
